name: 'Hello World'
description: 'Greet someone'
inputs:
    profile:
      required: true
      description: "The name of the publish profile to use. Must match the name (without extension) of a publish profile in the Properties/PublishProfiles folder of the project."
    variant:
      required: false
      default: "default"
      description: "The 'variant' of the build to be run - this is used when testing different auth modes for the same publish profile, for example."
    selfContained:
      default: "[true, false]"
      required: false
      description: "The values of self-contained to test this variant with. Some variants don't work with SC/FDD builds, so use this to control which ones are tested. Valid values are 'true', 'false', or '[true, false]' to test both."
    chunked:
      default: "[true, false]"
      required: false
      description: "Determines if the upload will be done with chunked or atomic uploads. Defaults to testing both. Values are 'true', 'false', or '[true, false]' to test both."

runs:
  using: "composite"
  steps:
    - name: Publish self contained, atomic
      shell: pwsh
      if: ${{ contains(fromJson(inputs.selfContained), true) }} && ${{ contains(fromJson(inputs.chunked), false) }}
      continue-on-error: true
      run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=${{ inputs.profile }} --self-contained true -p ContainerImageTags="""${{ inputs.variant }}-sc-atomic`;latest-sc-atomic""" /bl
      env:
        SDK_CONTAINER_DEBUG_REGISTRY_FORCE_CHUNKED_UPLOAD: 'false'

    - name: Archive binlog self-contained, atomic
      uses: actions/upload-artifact@v3
      if: ${{ contains(fromJson(inputs.selfContained), true) }} && ${{ contains(fromJson(inputs.chunked), false) }}
      with:
          name: ${{ inputs.profile}}-${{ inputs.variant }}-sc-atomic.binlog
          path: msbuild.binlog

    - name: Publish framework dependent, atomic
      shell: pwsh
      continue-on-error: true
      if: ${{ contains(fromJson(inputs.selfContained), false) }} && ${{ contains(fromJson(inputs.chunked), false) }}
      run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=${{ inputs.profile }} --self-contained false -p ContainerImageTags="""${{ inputs.variant }}-fdd-atomic`;latest-fdd-atomic""" /bl
      env:
        SDK_CONTAINER_DEBUG_REGISTRY_FORCE_CHUNKED_UPLOAD: 'false'

    - name: Archive binlog self-contained, atomic
      uses: actions/upload-artifact@v3
      if: ${{ contains(fromJson(inputs.selfContained), false) }} && ${{ contains(fromJson(inputs.chunked), false) }}
      with:
          name: ${{ inputs.profile}}-${{ inputs.variant }}-fdd-atomic.binlog
          path: msbuild.binlog

    - name: Publish self contained, chunked
      shell: pwsh
      continue-on-error: true
      if: ${{ contains(fromJson(inputs.selfContained), true) }} && ${{ contains(fromJson(inputs.chunked), true) }}
      run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=${{ inputs.profile }} --self-contained true -p ContainerImageTags="""${{ inputs.variant }}-sc-chunked`;latest-sc-chunked""" /bl
      env:
        SDK_CONTAINER_DEBUG_REGISTRY_FORCE_CHUNKED_UPLOAD: 'true'

    - name: Archive binlog self-contained, chunked
      uses: actions/upload-artifact@v3
      if: ${{ contains(fromJson(inputs.selfContained), true) }} && ${{ contains(fromJson(inputs.chunked), true) }}
      with:
          name: ${{ inputs.profile}}-${{ inputs.variant }}-sc-chunked.binlog
          path: msbuild.binlog

    - name: Publish framework dependent, chunked
      shell: pwsh
      continue-on-error: true
      if: ${{ contains(fromJson(inputs.selfContained), false) }} && ${{ contains(fromJson(inputs.chunked), true) }}
      run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=${{ inputs.profile }} --self-contained false -p ContainerImageTags="""${{ inputs.variant }}-fdd-chunked`;latest-fdd-chunked""" /bl
      env:
        SDK_CONTAINER_DEBUG_REGISTRY_FORCE_CHUNKED_UPLOAD: 'true'

    - name: Archive binlog self-contained, chunked
      uses: actions/upload-artifact@v3
      if: ${{ contains(fromJson(inputs.selfContained), false) }} && ${{ contains(fromJson(inputs.chunked), true) }}
      with:
          name: ${{ inputs.profile}}-${{ inputs.variant }}-fdd-chunked.binlog
          path: msbuild.binlog